Controllers/RoleAdminController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using UserIdentity.Identity;
using UserIdentity.Models;

namespace UserIdentity.Controllers
{
    [Authorize(Roles = "Admin")]
    public class RoleAdminController : Controller
    {
        private RoleManager<IdentityRole> RoleManager { get; set; }
        private UserManager<ApplicationUser> userManager;

        public RoleAdminController()
        {
            RoleManager = new RoleManager<IdentityRole>(new RoleStore<IdentityRole>(new IdentityDataContext()));
            userManager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(new IdentityDataContext()));
        }
        // GET: RoleAdmin
        public ActionResult Index()
        {
            return View(RoleManager.Roles);
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(string name)
        {
            if (ModelState.IsValid)
            {
                var result = RoleManager.Create(new IdentityRole((name)));
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    foreach (var resultError in result.Errors)
                    {
                        ModelState.AddModelError("", resultError);
                    }
                }
            }
            return View(name);
        }

        [HttpPost]
        public ActionResult Delete(string Id)
        {
            var role = RoleManager.FindById(Id);
            if (role != null)
            {
                var result = RoleManager.Delete(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    return View("Error", result.Errors);
                }
            }
            return View("Error", new string[] { "Role not found" });
        }
        [HttpGet]
        public ActionResult Edit(string Id)
        {
            var role = RoleManager.FindById(Id);

            var members = new List<ApplicationUser>();
            var nonMembers = new List<ApplicationUser>();

            foreach (var user in userManager.Users.ToList())
            {
                var list = userManager.IsInRole(user.Id, role.Name) ?
                    members : nonMembers;
                list.Add(user);
            }

            return View(new RoleEditModel()
            {
                Role = role,
                Members = members,
                NonMembers = nonMembers
            });
        }
        [HttpPost]
        public ActionResult Edit(RoleUpdateModel model)
        {
            IdentityResult result;
            if (ModelState.IsValid)
            {
                foreach (var userId in model.IdsToAdd ?? new string[] { })
                {
                    result = userManager.AddToRole(userId,model.RoleName);
                    if (!result.Succeeded)
                    {
                        return View("Error",result.Errors);
                    }
                }

                foreach (var userId in model.IdsToDelete ?? new string[]{})
                {
                    result = userManager.RemoveFromRole(userId,model.RoleName);
                    if (!result.Succeeded)
                    {
                        return View("Error", result.Errors);
                    }
                }

                return RedirectToAction("Index");
            }
            return View("Error", new string[]{"aranılan rol yok"});
        }
    }

}

Views/RoleAdmin/Create.cshtml
@{
    ViewBag.Title = "Create";
}

<h2>Create Role</h2>
<hr />
@Html.ValidationSummary()
@using (Html.BeginForm())
{
    <div class="form-group">
        <label>Name</label>
        <input name="name" value="@Model" class="form-control">
    </div>
    <button type="submit" class="btn btn-primary">Create</button>
}

Views/RoleAdmin/Edit.cshtml
@model UserIdentity.Models.RoleEditModel
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
<hr />
@using (Html.BeginForm())
{
    <input type="hidden" name="RoleName" value="@Model.Role.Name" />
    <input type="hidden" name="RoleId" value="@Model.Role.Id" />

    <div class="panel panel-primary">
        <div class="panel-heading">
            Add to @Model.Role.Name
        </div>
    </div>
    <table class="table table-striped">
        @if (Model.NonMembers.Count() == 0)
        {
            <tr> <td colspan="2">Bu role atanabilecek kullanıcı yok</td></tr>
        }
        else
        {
            <tr>
                <td>User Id</td>
                <td>User</td>
            </tr>
            foreach (var user in Model.NonMembers)
            {
                <tr>
                    <td>@user.UserName</td>
                    <td><input type="checkbox" name="IdsToAdd" value="@user.Id" /></td>
                </tr>
            }
        }
    </table>
    <div class="panel panel-primary">
        <div class="panel-heading">
            Remove from @Model.Role.Name
        </div>
    </div>
    <table class="table table-striped">
        @if (Model.Members.Count() == 0)
        {
            <tr> <td colspan="2">Bu role eklenmiş bir kullanıcı yok</td></tr>
        }
        else
        {
            <tr>
                <td>User Id</td>
                <td>User</td>
            </tr>
            foreach (var user in Model.Members)
            {
                <tr>
                    <td>@user.UserName</td>
                    <td><input type="checkbox" name="IdsToDelete" value="@user.Id" /></td>
                </tr>
            }
        }
    </table>
    <button type="submit" class="btn btn-primary">Save</button>

}

Views/RoleAdmin/Index.cshtml
@model IEnumerable<Microsoft.AspNet.Identity.EntityFramework.IdentityRole>
@{
    ViewBag.Title = "Index";
}

<h2>Roller</h2>
<hr />
<div class="panel panel-primary">
    <div class="panel-heading">
        Roller
    </div>
    <table class="table table-striped">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th></th>
        </tr>
        @if (Model.Count() == 0)
        {
            <tr>
                <td colspan="3">Rol Yok</td>
            </tr>
        }
        else
        {
            foreach (var role in Model)
            {
                <tr>
                    <td>
                        @role.Id
                    </td>
                    <td>
                        @role.Name
                    </td>
                    <td>
                        @using (Html.BeginForm("Delete", "RoleAdmin", new { Id = role.Id }))
                        {
                            <button type="submit" class="btn btn-danger btn-sm">Delete</button>
                            @Html.ActionLink("Edit", "Edit", new { Id = role.Id }, new { @class = "btn btn-primary btn-sm" })
                        }

                    </td>
                </tr>
            }
        }
    </table>
</div>